apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-postgres
  labels:
    app: docker-postgres
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: docker-postgres
  template:
    metadata:
      labels:
        app: docker-postgres
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "spring-maven-postgres-docker-k8s-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: docker-postgres
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.postgresImage.repository }}:{{ .Values.postgresImage.tag }}"
          env:
          - name: POSTGRES_USER
            value: dbuser
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_DB
            value: store
          imagePullPolicy: {{ .Values.postgresImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgresImage.containerPort }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

